# Generated by Django 5.2.5 on 2025-10-14 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0007_alter_patient_status_servicereceived'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCancerousMedsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('interpretation_of_result', models.CharField(choices=[('Negative', 'Negative'), ('ASC-US', 'ASC-US'), ('HPV Positive', 'HPV Positive'), ('Unsatisfactory', 'Unsatisfactory'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('release_date_of_meds', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='precancerous_meds_requests', to='patient.patient', to_field='patient_id')),
            ],
        ),
    ]
