# Generated by Django 5.2.5 on 2025-10-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precancerous', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precancerousmedsrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Completed', 'Complete')], default='Pending', max_length=20),
        ),
    ]
