# Generated by Django 5.2.5 on 2025-10-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precancerous', '0002_alter_precancerousmedsrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='precancerousmedsrequest',
            name='destination_name',
            field=models.CharField(default='Argao', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='precancerousmedsrequest',
            name='request_destination',
            field=models.CharField(default='Argao', max_length=200),
            preserve_default=False,
        ),
    ]
