# Generated by Django 5.2.5 on 2025-08-21 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RHU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgu', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('representative_first_name', models.CharField(max_length=150)),
                ('representative_last_name', models.CharField(max_length=150)),
                ('official_representative_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rhu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RHU Profile',
                'verbose_name_plural': 'RHU Profiles',
                'ordering': ['lgu', 'official_representative_name'],
            },
        ),
    ]
