# Generated by Django 5.2.5 on 2025-10-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhu',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='rhu/avatar/'),
        ),
    ]
