# Generated by Django 5.2.3 on 2025-07-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='temp1234', max_length=128),
            preserve_default=False,
        ),
    ]
