# Generated by Django 5.2.5 on 2025-09-07 06:43

import apps.cancer_management.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0006_diagnosisbasis_distantmetastasissite_primarysite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellBeingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('general_status', models.CharField(blank=True, max_length=255, null=True)),
                ('improve', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WellBeingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=255)),
                ('text_ceb', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CancerTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('radiotherapy', 'Radiation Therapy'), ('radioactive_therapy', 'Radioactive Therapy'), ('brachytherapy', 'Brachytherapy'), ('chemotherapy', 'Chemotherapy'), ('surgery', 'Surgery')], max_length=50)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('uploaded_result', models.FileField(blank=True, null=True, upload_to='attachments/result/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_treatment', to='patient.patient')),
                ('wellbeing_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cancer_management.wellbeingassessment')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.cancer_management.models.service_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cancer_treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cancer_management.cancertreatment')),
            ],
        ),
        migrations.CreateModel(
            name='WellBeingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Agree'), (4, 'Strongly Agree')])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cancer_management.wellbeingassessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cancer_management.wellbeingquestion')),
            ],
        ),
    ]
