# Generated by Django 5.2.5 on 2025-09-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_management', '0002_default_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancertreatment',
            name='service_type',
            field=models.CharField(max_length=50),
        ),
    ]
