# Generated by Django 5.2.5 on 2025-09-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_management', '0003_alter_cancertreatment_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancertreatment',
            name='service_type',
            field=models.CharField(choices=[('radiotherapy', 'Radiation Therapy'), ('radioactive_therapy', 'Radioactive Therapy'), ('brachytherapy', 'Brachytherapy'), ('chemotherapy', 'Chemotherapy'), ('surgery', 'Surgery')], max_length=50),
        ),
    ]
