# Generated by Django 5.2.5 on 2025-09-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_management', '0004_alter_cancertreatment_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancertreatment',
            name='service_type',
            field=models.CharField(choices=[('Radiotherapy', 'Radiation Therapy'), ('Radioactive Therapy', 'Radioactive Therapy'), ('Brachytherapy', 'Brachytherapy'), ('Chemotherapy', 'Chemotherapy'), ('Surgery', 'Surgery')], max_length=50),
        ),
    ]
