# Generated by Django 5.2.5 on 2025-09-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_management', '0005_alter_cancertreatment_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancertreatment',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancertreatment',
            name='treatment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancertreatment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Interview Process', 'Interview Process'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
