# Generated by Django 5.2.5 on 2025-09-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_management', '0006_cancertreatment_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancertreatment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Interview Process', 'Interview Process'), ('Approved', 'Approved'), ('Case Summary Generation', 'Case Summary Generation'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
