# Generated by Django 5.2.5 on 2025-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_management', '0007_alter_cancertreatment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancertreatment',
            name='has_patient_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancertreatment',
            name='response_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
