# Generated by Django 5.2.5 on 2025-10-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_management', '0008_cancertreatment_has_patient_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancertreatment',
            name='service_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
