# Generated by Django 5.2.3 on 2025-07-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DistantMetastasisSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('loa_generated', models.FileField(blank=True, null=True, upload_to='attachments/loa/')),
                ('loa_uploaded', models.FileField(blank=True, null=True, upload_to='attachments/loa/')),
                ('uploaded_result', models.FileField(blank=True, null=True, upload_to='attachments/result/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreScreeningForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_from', models.CharField(blank=True, max_length=255)),
                ('referring_doctor_or_facility', models.CharField(blank=True, max_length=255)),
                ('reason_for_referral', models.TextField(blank=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('date_of_consultation', models.DateField(blank=True, null=True)),
                ('date_of_diagnosis', models.DateField(blank=True, null=True)),
                ('multiple_primaries', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('primary_sites_other', models.CharField(blank=True, max_length=255)),
                ('laterality', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Not Stated', 'Not Stated'), ('Bilateral', 'Bilateral'), ('Mid', 'Mid')], max_length=50)),
                ('histology', models.CharField(blank=True, max_length=255)),
                ('staging', models.CharField(blank=True, choices=[('In-Situ', 'In-Situ'), ('Localized', 'Localized'), ('Direct Extension', 'Direct Extension'), ('Regional Lymph Node', 'Regional Lymph Node'), ('3+4', '3+4'), ('Distant Metastasis', 'Distant Metastasis'), ('Unknown', 'Unknown')], max_length=50)),
                ('t_system', models.CharField(blank=True, max_length=2)),
                ('n_system', models.CharField(blank=True, max_length=2)),
                ('m_system', models.CharField(blank=True, max_length=2)),
                ('distant_metastasis_sites_other', models.CharField(blank=True, max_length=255)),
                ('final_diagnosis', models.TextField(blank=True)),
                ('final_diagnosis_icd10', models.CharField(blank=True, max_length=50)),
                ('treatment_purpose', models.CharField(blank=True, choices=[('Curative-Complete', 'Curative-Complete'), ('Curative-Incomplete', 'Curative-Incomplete'), ('Palliative Only', 'Palliative Only')], max_length=50)),
                ('treatment_purpose_other', models.CharField(blank=True, max_length=255)),
                ('primary_assistance_by_ejacc', models.CharField(blank=True, max_length=255)),
                ('date_of_assistance', models.DateField(blank=True, null=True)),
                ('adjuvant_treatments_other', models.CharField(blank=True, max_length=255)),
                ('other_source_treatments_other', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimarySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_procedure_name', models.CharField(blank=True, max_length=100)),
                ('procedure_details', models.CharField(blank=True, max_length=200)),
                ('cancer_site', models.CharField(blank=True, max_length=100)),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='attachments/medical_certificates/')),
                ('laboratory_results', models.FileField(blank=True, null=True, upload_to='attachments/laboratory_results/')),
                ('barangay_certificate_of_indigency', models.FileField(blank=True, null=True, upload_to='attachments/barangay_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
