# Generated by Django 5.2.3 on 2025-07-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cancer_screening', '0001_initial'),
        ('patient', '0001_initial'),
        ('pre_enrollment', '0004_beneficiary_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualscreening',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_screening', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='prescreeningform',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_screening_form', to='pre_enrollment.beneficiary'),
        ),
        migrations.AddField(
            model_name='prescreeningform',
            name='diagnosis_basis',
            field=models.ManyToManyField(blank=True, to='cancer_screening.diagnosisbasis'),
        ),
        migrations.AddField(
            model_name='prescreeningform',
            name='distant_metastasis_sites',
            field=models.ManyToManyField(blank=True, to='cancer_screening.distantmetastasissite'),
        ),
        migrations.AddField(
            model_name='individualscreening',
            name='pre_screening_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer_screening.prescreeningform'),
        ),
        migrations.AddField(
            model_name='prescreeningform',
            name='primary_sites',
            field=models.ManyToManyField(blank=True, to='cancer_screening.primarysite'),
        ),
        migrations.AddField(
            model_name='screeningprocedure',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_procedure', to='pre_enrollment.beneficiary'),
        ),
        migrations.AddField(
            model_name='individualscreening',
            name='screening_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancer_screening.screeningprocedure'),
        ),
        migrations.AddField(
            model_name='prescreeningform',
            name='adjuvant_treatments_received',
            field=models.ManyToManyField(blank=True, related_name='adjuvant_treatments', to='cancer_screening.treatmentoption'),
        ),
        migrations.AddField(
            model_name='prescreeningform',
            name='other_source_treatments',
            field=models.ManyToManyField(blank=True, related_name='other_source_treatments', to='cancer_screening.treatmentoption'),
        ),
    ]
