# Generated by Django 5.2.3 on 2025-07-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningprocedure',
            name='barangay_certificate_of_indigency',
        ),
        migrations.RemoveField(
            model_name='screeningprocedure',
            name='laboratory_results',
        ),
        migrations.RemoveField(
            model_name='screeningprocedure',
            name='medical_certificate',
        ),
        migrations.CreateModel(
            name='ScreeningAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/screening_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('screening_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cancer_screening.screeningprocedure')),
            ],
        ),
    ]
