# Generated by Django 5.2.3 on 2025-07-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0003_remove_screeningprocedure_barangay_certificate_of_indigency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescreeningform',
            name='laterality',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Not Stated', 'Not Stated'), ('Bilateral', 'Bilateral'), ('Mild', 'Mild')], max_length=50),
        ),
    ]
