# Generated by Django 5.2.3 on 2025-07-26 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0004_alter_prescreeningform_laterality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualscreening',
            name='screening_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cancer_screening.screeningprocedure'),
        ),
    ]
