# Generated by Django 5.2.3 on 2025-07-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0005_alter_individualscreening_screening_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualscreening',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Next Steps Needed', 'Next Steps Needed'), ('Validation Required', 'Validation Required'), ('LOA Required', 'LOA Required'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
