# Generated by Django 5.2.3 on 2025-07-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0006_alter_individualscreening_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualscreening',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualscreening',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Next Steps Needed', 'Next Steps Needed'), ('Validation Required', 'Validation Required'), ('LOA Required', 'LOA Required'), ('LOA Uploaded', 'LOA Uploaded'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
