# Generated by Django 5.2.3 on 2025-08-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0007_individualscreening_date_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualscreening',
            name='has_patient_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualscreening',
            name='response_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individualscreening',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('LOA Generation', 'LOA Generation'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
