# Generated by Django 5.2.3 on 2025-08-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0008_individualscreening_has_patient_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualscreening',
            name='screening_schedule',
            field=models.DateField(blank=True, null=True),
        ),
    ]
