# Generated by Django 5.2.3 on 2025-08-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0009_individualscreening_screening_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualscreening',
            old_name='screening_schedule',
            new_name='screening_date',
        ),
    ]
