# Generated by Django 5.2.3 on 2025-08-10 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0010_rename_screening_schedule_individualscreening_screening_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualscreening',
            name='screening_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cancer_screening.screeningprocedure'),
        ),
    ]
