# Generated by Django 5.2.3 on 2025-08-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0011_alter_individualscreening_screening_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualscreening',
            name='loa_uploaded',
        ),
        migrations.AlterField(
            model_name='individualscreening',
            name='pre_screening_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cancer_screening.prescreeningform'),
        ),
        migrations.AlterField(
            model_name='individualscreening',
            name='screening_procedure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cancer_screening.screeningprocedure'),
        ),
        migrations.AlterField(
            model_name='individualscreening',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('LOA Generation', 'LOA Generation'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Reject', 'Reject')], default='Pending', max_length=50),
        ),
    ]
