# Generated by Django 5.2.5 on 2025-08-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0012_remove_individualscreening_loa_uploaded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualscreening',
            name='pre_screening_form',
        ),
        migrations.AddField(
            model_name='individualscreening',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PreScreeningForm',
        ),
    ]
