# Generated by Django 5.2.5 on 2025-08-23 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0013_remove_individualscreening_pre_screening_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreScreeningForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_from', models.CharField(blank=True, max_length=255)),
                ('referring_doctor_or_facility', models.CharField(blank=True, max_length=255)),
                ('reason_for_referral', models.TextField(blank=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('date_of_consultation', models.DateField(blank=True, null=True)),
                ('date_of_diagnosis', models.DateField(blank=True, null=True)),
                ('multiple_primaries', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('primary_sites_other', models.CharField(blank=True, max_length=255)),
                ('laterality', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Not Stated', 'Not Stated'), ('Bilateral', 'Bilateral'), ('Mild', 'Mild')], max_length=50)),
                ('histology', models.CharField(blank=True, max_length=255)),
                ('staging', models.CharField(blank=True, choices=[('In-Situ', 'In-Situ'), ('Localized', 'Localized'), ('Direct Extension', 'Direct Extension'), ('Regional Lymph Node', 'Regional Lymph Node'), ('3+4', '3+4'), ('Distant Metastasis', 'Distant Metastasis'), ('Unknown', 'Unknown')], max_length=50)),
                ('t_system', models.CharField(blank=True, max_length=2)),
                ('n_system', models.CharField(blank=True, max_length=2)),
                ('m_system', models.CharField(blank=True, max_length=2)),
                ('distant_metastasis_sites_other', models.CharField(blank=True, max_length=255)),
                ('final_diagnosis', models.TextField(blank=True)),
                ('final_diagnosis_icd10', models.CharField(blank=True, max_length=50)),
                ('treatment_purpose', models.CharField(blank=True, choices=[('Curative-Complete', 'Curative-Complete'), ('Curative-Incomplete', 'Curative-Incomplete'), ('Palliative Only', 'Palliative Only')], max_length=50)),
                ('treatment_purpose_other', models.CharField(blank=True, max_length=255)),
                ('primary_assistance_by_ejacc', models.CharField(blank=True, max_length=255)),
                ('date_of_assistance', models.DateField(blank=True, null=True)),
                ('adjuvant_treatments_other', models.CharField(blank=True, max_length=255)),
                ('other_source_treatments_other', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjuvant_treatments_received', models.ManyToManyField(blank=True, related_name='adjuvant_treatments', to='cancer_screening.treatmentoption')),
                ('diagnosis_basis', models.ManyToManyField(blank=True, to='cancer_screening.diagnosisbasis')),
                ('distant_metastasis_sites', models.ManyToManyField(blank=True, to='cancer_screening.distantmetastasissite')),
                ('individual_screening', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_screening_form', to='cancer_screening.individualscreening')),
                ('other_source_treatments', models.ManyToManyField(blank=True, related_name='other_source_treatments', to='cancer_screening.treatmentoption')),
                ('primary_sites', models.ManyToManyField(blank=True, to='cancer_screening.primarysite')),
            ],
        ),
    ]
