# Generated by Django 5.2.5 on 2025-08-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0014_prescreeningform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualscreening',
            name='screening_procedure',
        ),
        migrations.RemoveField(
            model_name='screeningprocedure',
            name='beneficiary',
        ),
    ]
