# Generated by Django 5.2.5 on 2025-08-24 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0015_remove_individualscreening_screening_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningprocedure',
            name='individual_screening',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='screening_procedure', to='cancer_screening.individualscreening'),
            preserve_default=False,
        ),
    ]
