# Generated by Django 5.2.5 on 2025-08-24 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0016_screeningprocedure_individual_screening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningprocedure',
            name='individual_screening',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_procedure', to='cancer_screening.individualscreening'),
        ),
    ]
