# Generated by Django 5.2.5 on 2025-08-30 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0017_alter_screeningprocedure_individual_screening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningattachment',
            name='screening_procedure',
        ),
        migrations.AddField(
            model_name='individualscreening',
            name='cancer_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individualscreening',
            name='procedure_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='individualscreening',
            name='procedure_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='screeningattachment',
            name='individual_screening',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='screening_attachments', to='cancer_screening.individualscreening'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ScreeningProcedure',
        ),
    ]
