# Generated by Django 5.2.5 on 2025-08-31 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0017_alter_screeningprocedure_individual_screening'),
        ('patient', '0005_patient_registered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCancerousMedsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgu_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('prepared_by', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=2)),
                ('date_of_birth', models.DateField()),
                ('interpretation_of_result', models.CharField(choices=[('Negative', 'Negative'), ('ASC-US', 'ASC-US'), ('HPV Positive', 'HPV Positive'), ('Unsatisfactory', 'Unsatisfactory'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precancerous_meds_requests', to='patient.patient')),
            ],
        ),
    ]
