# Generated by Django 5.2.5 on 2025-08-31 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0018_precancerousmedsrequest'),
        ('patient', '0005_patient_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precancerousmedsrequest',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='precancerous_meds_requests', to='patient.patient', to_field='patient_id'),
        ),
    ]
