# Generated by Django 5.2.5 on 2025-08-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0020_reorder_precancerous_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='precancerousmedsrequest',
            name='release_date_of_meds',
            field=models.DateField(blank=True, null=True),
        ),
    ]
