# Generated by Django 5.2.3 on 2025-09-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0018_remove_screeningattachment_screening_procedure_and_more'),
        ('cancer_screening', '0021_precancerousmedsrequest_release_date_of_meds'),
    ]

    operations = [
    ]
