# Generated by Django 5.2.5 on 2025-08-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0018_remove_screeningattachment_screening_procedure_and_more'),
        ('cancer_screening', '0021_precancerousmedsrequest_release_date_of_meds'),
    ]

    operations = [
    ]
