# Generated by Django 5.2.5 on 2025-09-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0022_merge_20250831_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precancerousmedsrequest',
            options={'managed': False},
        ),
    ]
