# Generated by Django 5.2.5 on 2025-09-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0022_merge_20250901_2210'),
        ('cancer_screening', '0023_alter_precancerousmedsrequest_options'),
    ]

    operations = [
    ]
