# Generated by Django 5.2.5 on 2025-09-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0022_merge_20250902_1751'),
        ('cancer_screening', '0024_merge_20250902_2037'),
    ]

    operations = [
    ]
