# Generated by Django 5.2.5 on 2025-09-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0025_merge_20250903_1946'),
        ('cancer_screening', '0025_merge_20250903_2104'),
    ]

    operations = [
    ]
