# Generated by Django 5.2.6 on 2025-09-06 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0025_merge_20250903_1946'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='precancerousmedsrequest',
            table='cancer_screening_precancerousmedsrequest',
        ),
    ]
