# Generated by Django 5.2.5 on 2025-09-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0026_merge_20250905_0928'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='precancerousmedsrequest',
            table='cancer_screening_precancerousmedsrequest',
        ),
    ]
