# Generated by Django 5.2.5 on 2025-09-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0027_alter_precancerousmedsrequest_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescreeningform',
            name='diagnosis_basis',
        ),
        migrations.RemoveField(
            model_name='prescreeningform',
            name='distant_metastasis_sites',
        ),
        migrations.RemoveField(
            model_name='prescreeningform',
            name='adjuvant_treatments_received',
        ),
        migrations.RemoveField(
            model_name='prescreeningform',
            name='individual_screening',
        ),
        migrations.RemoveField(
            model_name='prescreeningform',
            name='other_source_treatments',
        ),
        migrations.RemoveField(
            model_name='prescreeningform',
            name='primary_sites',
        ),
        migrations.RemoveField(
            model_name='individualscreening',
            name='loa_generated',
        ),
        migrations.DeleteModel(
            name='DiagnosisBasis',
        ),
        migrations.DeleteModel(
            name='DistantMetastasisSite',
        ),
        migrations.DeleteModel(
            name='TreatmentOption',
        ),
        migrations.DeleteModel(
            name='PreScreeningForm',
        ),
        migrations.DeleteModel(
            name='PrimarySite',
        ),
    ]
