# Generated by Django 5.2.5 on 2025-09-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0028_remove_prescreeningform_diagnosis_basis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualscreening',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Reject', 'Reject')], default='Pending', max_length=50),
        ),
    ]
