# Generated by Django 5.2.5 on 2025-09-21 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0028_remove_prescreeningform_diagnosis_basis_and_more'),
        ('rhu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassScreeningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('beneficiaries', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('support_need', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rhu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_screening_requests', to='rhu.rhu')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MassScreeningAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/mass_screening/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cancer_screening.massscreeningrequest')),
            ],
        ),
    ]
