# Generated by Django 5.2.5 on 2025-09-21 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0029_massscreeningrequest_massscreeningattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassScreeningAttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to='cancer_screening.massscreeningrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
