# Generated by Django 5.2.3 on 2025-09-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0029_alter_individualscreening_status'),
        ('cancer_screening', '0030_massscreeningattendanceentry'),
    ]

    operations = [
    ]
