# Generated by Django 5.2.5 on 2025-09-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0031_merge_20250922_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningattachment',
            name='doc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
