# Generated by Django 5.2.5 on 2025-10-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0032_screeningattachment_doc_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreCancerousMedsRequest',
        ),
    ]
