# Generated by Django 5.2.5 on 2025-10-21 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0034_alter_massscreeningrequest_rhu'),
        ('partners', '0003_private_privaterepresentative'),
        ('rhu', '0004_backfill_rhuv2_from_rhu'),
    ]

    operations = [
        migrations.AddField(
            model_name='massscreeningrequest',
            name='private',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mass_screening_requests', to='partners.private'),
        ),
        migrations.AlterField(
            model_name='massscreeningrequest',
            name='rhu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mass_screening_requests', to='rhu.rhuv2'),
        ),
    ]
