# Generated by Django 5.2.5 on 2025-10-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0035_massscreeningrequest_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualscreening',
            name='service_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
