# Generated by Django 5.2.7 on 2025-10-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0036_individualscreening_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualscreening',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('In Progress', 'In Progress'), ('Completed', 'Complete'), ('Rejected', 'Reject')], default='Pending', max_length=50),
        ),
    ]
