# Generated by Django 5.2.7 on 2025-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0037_alter_individualscreening_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualscreening',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Completed', 'Complete'), ('Rejected', 'Reject')], default='Pending', max_length=50),
        ),
    ]
