# Generated by Django 5.2.8 on 2025-11-23 03:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_screening', '0039_alter_individualscreening_uploaded_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massscreeningattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='document'),
        ),
    ]
