# Generated by Django 5.2.5 on 2025-09-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0007_alter_patient_status_servicereceived'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Reject', 'Reject')], default='Pending', max_length=50)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('uploaded_result', models.FileField(blank=True, null=True, upload_to='attachments/result/')),
                ('has_patient_response', models.BooleanField(default=False)),
                ('response_description', models.CharField(blank=True, max_length=255, null=True)),
                ('laboratory_test_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_treatment', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/post_treatment_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('post_treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_attachments', to='post_treatment.posttreatment')),
            ],
        ),
    ]
