# Generated by Django 5.2.5 on 2025-09-29 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_status_servicereceived'),
        ('post_treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupCheckups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_checkups', to='patient.patient')),
            ],
            options={
                'verbose_name': 'FollowupCheckup',
                'verbose_name_plural': 'FollowupCheckups',
            },
        ),
    ]
