# Generated by Django 5.2.5 on 2025-09-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_treatment', '0002_followupcheckups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttreatment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('In Progress', 'In Progress'), ('Completed', 'Complete'), ('Rejected', 'Reject')], default='Pending', max_length=50),
        ),
    ]
