# Generated by Django 5.2.5 on 2025-09-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_treatment', '0003_alter_posttreatment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttreatment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Completed', 'Complete'), ('Follow-up Required', 'Follow-up Required'), ('Closed', 'Close'), ('Rejected', 'Reject')], default='Pending', max_length=50),
        ),
    ]
