# Generated by Django 5.2.5 on 2025-09-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_treatment', '0004_alter_posttreatment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupcheckups',
            name='patient',
        ),
        migrations.AddField(
            model_name='followupcheckups',
            name='post_treatment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followup_checkups', to='post_treatment.posttreatment'),
            preserve_default=False,
        ),
    ]
