# Generated by Django 5.2.5 on 2025-10-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_treatment', '0005_remove_followupcheckups_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttreatment',
            name='service_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
