# Generated by Django 5.2.3 on 2025-06-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_enrollment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='beneficiary_code',
            new_name='beneficiary_id',
        ),
    ]
