# Generated by Django 5.2.3 on 2025-06-29 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_enrollment', '0003_rename_beneficiary_code_beneficiary_beneficiary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
