# Generated by Django 5.2.5 on 2025-09-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_enrollment', '0004_beneficiary_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='beneficiary',
        ),
        migrations.DeleteModel(
            name='Beneficiary',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
