// src/constants/requiredDocs.js
export const REQUIRED_DOCS = {
  Radiotherapy: [
    { key: "quotation", label: "Quotation" },
    { key: "letter", label: "Letter of Request" },
    { key: "abstract", label: "Medical Abstract" },
    { key: "caseStudy", label: "Case Study Report" },
    { key: "sketch", label: "Sketch of Address" },
    { key: "incomeTax", label: "Income Tax Report" },
    { key: "barangay", label: "Barangay Indigency" },
  ],
  "Radioactive Therapy": [
    { key: "quotation", label: "Quotation" },
    { key: "letter", label: "Letter of Request" },
    { key: "abstract", label: "Medical Abstract" },
    { key: "caseStudy", label: "Case Study Report" },
    { key: "sketch", label: "Sketch of Address" },
    { key: "incomeTax", label: "Income Tax Report" },
    { key: "barangay", label: "Barangay Indigency" },
  ],
  Brachytherapy: [
    { key: "quotation", label: "Quotation" },
    { key: "letter", label: "Letter of Request" },
    { key: "abstract", label: "Medical Abstract" },
    { key: "caseStudy", label: "Case Study Report" },
    { key: "sketch", label: "Sketch of Address" },
    { key: "incomeTax", label: "Income Tax Report" },
    { key: "barangay", label: "Barangay Indigency" },
  ],
  Chemotherapy: [
    { key: "biopsy", label: "Biopsy Result" },
    { key: "abstract", label: "Medical Abstract" },
    { key: "sketch", label: "Sketch of Address" },
    { key: "protocol", label: "Treatment Protocol" },
    { key: "barangay", label: "Barangay Indigency" },
    { key: "letter", label: "Letter of Request" },
    { key: "caseStudy", label: "Case Study Report" },
    { key: "incomeTax", label: "Income Tax Report" },
  ],
  Surgery: [
    { key: "endorsement", label: "Endorsement from social service" },
    { key: "abstract", label: "Medical Abstract" },
    { key: "sketch", label: "Sketch of Address" },
    { key: "biopsy", label: "Biopsy Result" },
    { key: "barangay", label: "Barangay Indigency" },
    { key: "letter", label: "Letter of Request" },
    { key: "caseStudy", label: "Case Study Report" },
    { key: "incomeTax", label: "Income Tax Report" },
  ],
  "Individual Screening": [
    { key: "medCert", label: "Medical Certificate" },
    { key: "labResults", label: "Laboratory Results" },
    { key: "barangay", label: "Barangay Indigency" },
  ],
  "Post Treatment": [
    { key: "labRequest", label: "Laboratory Request" },
  ],
  "Hormonal Replacement": [
    { key: "docPrisc", label: "Doctor's Prescription" },
  ],
};
