# Generated by Django 5.2.5 on 2025-10-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychosocial_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='patients',
            field=models.TextField(blank=True, default=''),
        ),
    ]
