# Generated by Django 5.2.7 on 2025-11-09 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_status_servicereceived'),
        ('psychosocial_support', '0002_alter_activity_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychosocialAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='psychosocial_support.activity')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyschosocial_attendances', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Psychosocial Activity Attendance',
                'verbose_name_plural': 'Psychosocial Activity Attendances',
                'unique_together': {('activity', 'patient')},
            },
        ),
    ]
