# Generated by Django 5.2.8 on 2025-11-23 02:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychosocial_support', '0003_psychosocialattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
