# Generated by Django 5.2.3 on 2025-07-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pre_enrollment', '0004_beneficiary_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='pre_enrollment.beneficiary')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['beneficiary__last_name', 'beneficiary__first_name'],
            },
        ),
        migrations.CreateModel(
            name='CancerDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('date_diagnosed', models.DateField(blank=True, null=True)),
                ('cancer_site', models.CharField(blank=True, max_length=100, null=True)),
                ('cancer_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patient.patient')),
            ],
        ),
    ]
