# Generated by Django 5.2.3 on 2025-08-20 07:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='beneficiary',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='Bogo, Argao, Cebu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='barangay',
            field=models.CharField(default='Bogo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='Argao', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(choices=[('single', 'Single'), ('co-habitation', 'Co-Habitation'), ('separated', 'Separated'), ('widower', 'Widower'), ('married', 'Married'), ('annulled', 'Annulled')], default='single', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 8, 20, 7, 33, 27, 329563, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='dmarklouil@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='Mark Louil', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='highest_educational_attainment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='Diacamos', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(default='232323232', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_rafi_programs_availed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='source_of_income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='source_of_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('validated', 'Validated'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship_to_patient', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('landline_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['created_at'],
            },
        ),
    ]
