# Generated by Django 5.2.3 on 2025-08-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_options_remove_patient_beneficiary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancerdiagnosis',
            options={'verbose_name': 'CancerDiagnosis', 'verbose_name_plural': 'CancerDiagnosis'},
        ),
    ]
