# Generated by Django 5.2.5 on 2025-08-23 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_cancerdiagnosis_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_updates', to='patient.patient')),
            ],
            options={
                'verbose_name': 'HistoricalUpdate',
                'verbose_name_plural': 'HistoricalUpdates',
            },
        ),
    ]
