# Generated by Django 5.2.5 on 2025-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_historicalupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='registered_by',
            field=models.CharField(choices=[('rafi', 'Rafi'), ('rhu', 'Rhu'), ('private', 'Private'), ('self', 'Self')], default='self', max_length=20),
            preserve_default=False,
        ),
    ]
