# Generated by Django 5.2.5 on 2025-09-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_diagnosisbasis_distantmetastasissite_primarysite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('validated', 'Validated'), ('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_received', to='patient.patient')),
            ],
            options={
                'verbose_name': 'ServiceReceived',
                'verbose_name_plural': 'ServicesReceived',
            },
        ),
    ]
