# Generated by Django 5.2.7 on 2025-11-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_status_servicereceived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registered_by',
            field=models.CharField(default='Self', max_length=20),
        ),
    ]
