# Generated by Django 5.2.8 on 2025-11-22 08:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_patient_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
