# Generated by Django 5.2.5 on 2025-11-22 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_alter_cancerawarenessactivity_uploader'),
        ('patient', '0008_alter_patient_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='private',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='partners.private'),
        ),
    ]
