# Generated by Django 5.2.3 on 2025-08-17 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerAwarenessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cancer_awareness_activity/photos/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/cancer_awareness_activity/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_awareness_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
