# Generated by Django 5.2.3 on 2025-08-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancerawarenessactivity',
            options={'verbose_name': 'CancerAwarenessActivity', 'verbose_name_plural': 'CancerAwarenessActivities'},
        ),
    ]
