# Generated by Django 5.2.7 on 2025-11-09 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_private_privaterepresentative'),
        ('patient', '0007_alter_patient_status_servicereceived'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerAwarenessAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='partners.cancerawarenessactivity')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_awareness_attendances', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Cancer Awareness Attendance',
                'verbose_name_plural': 'Cancer Awareness Attendances',
                'unique_together': {('activity', 'patient')},
            },
        ),
    ]
