# Generated by Django 5.2.7 on 2025-11-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_cancerawarenessattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancerawarenessactivity',
            name='uploader',
            field=models.CharField(max_length=255),
        ),
    ]
