# Generated by Django 5.2.5 on 2025-10-02 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cancer_management', '0008_cancertreatment_has_patient_response_and_more'),
        ('patient', '0007_alter_patient_status_servicereceived'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHomeVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('recommendation', 'Recommendation'), ('closed', 'Close')], max_length=20)),
                ('date', models.DateField()),
                ('prepared_by', models.CharField(max_length=200)),
                ('approved_by', models.CharField(max_length=200)),
                ('purpose_of_visit', models.TextField()),
                ('findings', models.TextField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_visit', to='patient.patient')),
                ('wellbeing_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cancer_management.wellbeingassessment')),
            ],
        ),
    ]
