# Generated by Django 5.2.5 on 2025-10-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survivorship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthomevisit',
            old_name='date',
            new_name='visit_date',
        ),
    ]
