# Generated by Django 5.2.5 on 2025-10-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorship', '0002_rename_date_patienthomevisit_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthomevisit',
            name='signed_recommendation',
            field=models.FileField(default=1, upload_to='home_visit/signed_recommendation/'),
            preserve_default=False,
        ),
    ]
