# Generated by Django 5.2.5 on 2025-10-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorship', '0003_patienthomevisit_signed_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthomevisit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Recommendation', 'Recommendation'), ('Closed', 'Close')], max_length=20),
        ),
    ]
