# Generated by Django 5.2.5 on 2025-10-03 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_management', '0008_cancertreatment_has_patient_response_and_more'),
        ('survivorship', '0004_alter_patienthomevisit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthomevisit',
            name='findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthomevisit',
            name='purpose_of_visit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthomevisit',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthomevisit',
            name='signed_recommendation',
            field=models.FileField(blank=True, null=True, upload_to='home_visit/signed_recommendation/'),
        ),
        migrations.AlterField(
            model_name='patienthomevisit',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthomevisit',
            name='wellbeing_assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cancer_management.wellbeingassessment'),
        ),
    ]
