# Generated by Django 5.2.5 on 2025-10-13 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_status_servicereceived'),
        ('survivorship', '0005_alter_patienthomevisit_findings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HormonalReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Completed', 'Complete')], max_length=20)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('service_completed', models.CharField(max_length=100)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('medicines_requested', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hormonal_replacement', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HormonalReplacementRequiredAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/hormonal_replacement/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('hormonal_replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hormonal_replacement_required_attachments', to='survivorship.hormonalreplacement')),
            ],
        ),
    ]
