# Generated by Django 5.2.5 on 2025-10-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorship', '0006_hormonalreplacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hormonalreplacement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Completed', 'Complete')], default='Pending', max_length=20),
        ),
    ]
