# Generated by Django 5.2.5 on 2025-10-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorship', '0007_alter_hormonalreplacement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hormonalreplacement',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
