# Generated by Django 5.2.5 on 2025-10-13 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorship', '0008_hormonalreplacement_date_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hormonalreplacementrequiredattachment',
            name='hormonal_replacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_attachments', to='survivorship.hormonalreplacement'),
        ),
    ]
