# Generated by Django 5.2.5 on 2025-10-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorship', '0009_alter_hormonalreplacementrequiredattachment_hormonal_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='hormonalreplacement',
            name='has_patient_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hormonalreplacement',
            name='response_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patienthomevisit',
            name='has_patient_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patienthomevisit',
            name='response_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
