# Generated by Django 5.2.7 on 2025-11-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorship', '0010_hormonalreplacement_has_patient_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthomevisit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Recommendation', 'Recommendation'), ('Completed', 'Complete'), ('Closed', 'Close')], max_length=20),
        ),
    ]
