# Generated by Django 5.2.7 on 2025-11-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivorship', '0011_alter_patienthomevisit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hormonalreplacement',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Completed', 'Complete'), ('Rejected', 'Reject')], default='Pending', max_length=20),
        ),
    ]
