# Generated by Django 5.2.8 on 2025-11-23 01:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survivorship', '0012_alter_hormonalreplacement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hormonalreplacementrequiredattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='document'),
        ),
    ]
