# Generated by Django 5.2.3 on 2025-06-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_code',
            new_name='user_id',
        ),
    ]
