# Generated by Django 5.2.5 on 2025-08-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plain_password',
        ),
    ]
