# Generated by Django 5.2.5 on 2025-10-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
