# Generated by Django 5.2.5 on 2025-10-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_institution_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
